[Task 4] Dynamic connectivity
bozhnyukAlex/high-performance-graph-analysis-course pull request #4
Opened 2022-05-17 15:04 UTC by bozhnyukAlex

2022-05-17 22:07 UTC, katyacyfra requested changes
1. Стр 12 псевдокода, комментарий: _Будет заполняться при вызове f all от детей_ --- Возможен ли такой случай, когда рекурсивно вызываясь от ребёнка, мы так и не заполним это множество?
2. _Если BFS-дерево почти вырождается в список_ --- Насколько почти? Может ли оно полностью выродиться в список? А если не вырождается в список, то что тогда? 
3. _Если BFS-дерево почти вырождается в список, то его высота сравнима с d,_ --- Почему высота сравнима с d, можно подробнее? Как "вырождение дерева в список" делает высоту сравнимой с d?

2022-05-18 21:09 UTC, bozhnyukAlex commented
> Стр 12 псевдокода, комментарий: Будет заполняться при вызове fall от детей --- Возможен ли такой случай, когда рекурсивно вызываясь от ребёнка, мы так и не заполним это множество?

Я считаю, что такой случай невозможен. Пусть изначально вызвали fall(v). При рекурсивном вызове для ребенка u мы будем перебирать вершины из N2(u) и добавлять в их N3 множества вершину u (стр 5). В N2(u) окажется вершина v, так как до рекурсивного вызова мы пересчитываем множество N2(u) и её туда добавляли (стр 8).

2022-05-18 21:42 UTC, bozhnyukAlex commented
> Если BFS-дерево почти вырождается в список --- Насколько почти? Может ли оно полностью выродиться в список? А если не вырождается в список, то что тогда?

На фото ниже приведен пример. Красным выделено BFS-дерево, построенное по данному графу, корень в вершине 1. Если удалить ребро (1, 2), то изначальное BFS-дерево станет списком. "Почти список" нужен для оценки худшего случая количества вызовов fall для дерева. Например, в данном случае, если из изначального графа удалить ребро (1, 3), то придется ронять вершины 3, 4, 5, 6. При доказательстве случай, когда дерево не почти список, нас не интересует, так как там количество вызовов fall будет меньше.
![2022-05-19 00 31 56](https://user-images.githubusercontent.com/55096905/169159294-ab94d9c3-e7b4-4b20-8d9c-c39dde71ec9d.jpg)

2022-05-18 22:19 UTC, bozhnyukAlex commented
> Если BFS-дерево почти вырождается в список, то его высота сравнима с d, --- Почему высота сравнима с d, можно подробнее? Как "вырождение дерева в список" делает высоту сравнимой с d?

Я думаю, я здесь не совсем верно выразился. Почти список, как и в прошлой задаче, нужен для оценки максимального количества вызовов fall, как в примере из ответа на вопрос 2. При таком случае вызов fall может вызвать рекурсивный пересчет большого поддерева, как в случае с вершинами 3-6 в примере. По идее, высота такого дерева сравнима с d, потому что максимальная высота такого дерева - d, по условию.

2022-05-18 22:25 UTC, bozhnyukAlex commented
Исправил пару опечаток, а также подправил немного третье задание.

2022-05-19 20:58 UTC, katyacyfra approved these changes
Всё норм, 5 баллов (5 баллов снимаю за использование чужого решения)

2022-05-22 13:47 UTC, merged